apiVersion: v1
kind: Service
metadata:
  name: {{ include "passchain.fullname" . }}-backend
  labels:
    {{- include "passchain.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.nodePort }}
    nodePort: {{ .Values.backend.service.nodePort }}
    {{- end }}
  selector:
    {{- include "passchain.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend

